// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Event struct {
	Seq            int64
	ID             string
	Type           string
	IdempotencyKey string
	TsUnixMs       int64
	PayloadJson    string
}
