// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
)

const appendEvent = `-- name: AppendEvent :execrows
INSERT OR IGNORE INTO events (id, type, idempotency_key, ts_unix_ms, payload_json)
VALUES (?, ?, ?, ?, ?)
`

type AppendEventParams struct {
	ID             string
	Type           string
	IdempotencyKey string
	TsUnixMs       int64
	PayloadJson    string
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, appendEvent,
		arg.ID,
		arg.Type,
		arg.IdempotencyKey,
		arg.TsUnixMs,
		arg.PayloadJson,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const readEventsSince = `-- name: ReadEventsSince :many
SELECT seq, id, type, idempotency_key, ts_unix_ms, payload_json
FROM events
WHERE seq > ?
ORDER BY seq ASC
`

func (q *Queries) ReadEventsSince(ctx context.Context, seq int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, readEventsSince, seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.Type,
			&i.IdempotencyKey,
			&i.TsUnixMs,
			&i.PayloadJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
