import { defineWorkflow } from '../workflow/schema.js';

export const softwareDevAgileWorkflow = defineWorkflow({
  id: 'software-dev-agile',
  version: '1.0.0',
  name: '软件开发（敏捷）',
  description: 'Built-in agile software development workflow: requirements → PRD → design → sprint → parallel coding → QA → delivery',
  nodes: [
    {
      id: 'start',
      type: 'trigger',
      name: '启动',
    },
    {
      id: 'requirements',
      type: 'agent',
      name: '需求收集',
      agentRole: 'pm',
      executor: 'sonnet',
      artifacts: {
        consumes: [],
        produces: [
          { id: 'requirements-raw', path: 'docs/requirements/raw/requirements-raw.md' },
          { id: 'modules', path: 'docs/requirements/modules.md' },
        ],
      },
      outputValidator: { required: ['requirements-raw', 'modules'] },
      humanApproval: {
        message: '需求摘要已生成，请确认后继续',
        timeoutMs: 600_000,
        onTimeout: 'auto_approve',
        allowedActions: ['approve', 'reject', 'defer'],
        onReject: 'requirements',
      },
    },
    {
      id: 'prd',
      type: 'agent',
      name: 'PRD 编写',
      agentRole: 'pm',
      executor: 'sonnet',
      artifacts: {
        consumes: [{ id: 'requirements-raw' }, { id: 'modules' }],
        produces: [{ id: 'prd-doc', path: 'docs/design/prd/prd-v1.md' }],
      },
      outputValidator: { required: ['prd-doc'] },
      humanApproval: {
        message: 'PRD 已完成，请审核',
        timeoutMs: 1_800_000,
        onTimeout: 'auto_approve',
        allowedActions: ['approve', 'reject'],
        onReject: 'prd',
      },
    },
    {
      id: 'design',
      type: 'agent',
      name: '技术设计',
      agentRole: 'arch',
      executor: 'sonnet',
      artifacts: {
        consumes: [{ id: 'prd-doc' }],
        produces: [{ id: 'design-doc', path: 'docs/design/architecture/design-v1.md' }],
      },
      outputValidator: { required: ['design-doc'] },
    },
    {
      id: 'sprint-plan',
      type: 'agent',
      name: 'Sprint 规划',
      agentRole: 'pm',
      executor: 'sonnet',
      artifacts: {
        consumes: [{ id: 'design-doc' }],
        produces: [{ id: 'sprint-plan', path: 'docs/sprints/sprint-1/plan.md' }],
      },
    },
    {
      id: 'coding-fork',
      type: 'parallel_fork',
      name: '并行开发分叉',
    },
    {
      id: 'coding',
      type: 'agent',
      name: '编码',
      agentRole: 'coder',
      executor: 'sonnet',
      artifacts: {
        consumes: [{ id: 'sprint-plan' }, { id: 'design-doc' }],
        produces: [{ id: 'impl', path: 'src/implementation-complete.md' }],
      },
    },
    {
      id: 'coding-join',
      type: 'join',
      name: '等待编码完成',
    },
    {
      id: 'qa',
      type: 'agent',
      name: 'QA 测试',
      agentRole: 'qa',
      executor: 'sonnet',
      artifacts: {
        consumes: [{ id: 'impl' }],
        produces: [{ id: 'qa-report', path: 'docs/qa/report-v1.md' }],
      },
    },
    {
      id: 'qa-gate',
      type: 'condition',
      name: 'QA 通过判断',
    },
    {
      id: 'bug-fix',
      type: 'agent',
      name: '缺陷修复',
      agentRole: 'coder',
      executor: 'sonnet',
      artifacts: {
        consumes: [{ id: 'qa-report' }],
        produces: [{ id: 'impl', path: 'src/implementation-complete.md' }],
      },
    },
    {
      id: 'delivery',
      type: 'human_approval',
      name: 'Sprint 交付确认',
      humanApproval: {
        message: 'QA 通过，Sprint 已完成，请确认交付',
        timeoutMs: 600_000,
        onTimeout: 'auto_approve',
        allowedActions: ['approve', 'reject'],
        onReject: 'qa',
      },
    },
  ],
  edges: [
    { from: 'start', to: 'requirements', condition: 'success' },
    { from: 'requirements', to: 'prd', condition: 'approved' },
    { from: 'requirements', to: 'requirements', condition: 'rejected' },
    { from: 'prd', to: 'design', condition: 'approved' },
    { from: 'prd', to: 'prd', condition: 'rejected' },
    { from: 'design', to: 'sprint-plan', condition: 'success' },
    { from: 'sprint-plan', to: 'coding-fork', condition: 'success' },
    { from: 'coding-fork', to: 'coding', condition: 'success' },
    { from: 'coding', to: 'coding-join', condition: 'success' },
    { from: 'coding-join', to: 'qa', condition: 'success' },
    { from: 'qa', to: 'qa-gate', condition: 'success' },
    { from: 'qa-gate', to: 'delivery', condition: 'passed' },
    { from: 'qa-gate', to: 'bug-fix', condition: 'failed' },
    { from: 'bug-fix', to: 'qa', condition: 'success' },
  ],
});
