import { defineWorkflow } from '../../workflow/schema.js';

export const softwareDevAgileWorkflow = defineWorkflow({
  id: 'software-dev-agile',
  version: '1.0.0',
  name: 'Software Development (Agile)',
  description: 'Requirements → PRD → Design → Sprint planning → Parallel dev → QA → Delivery',
  nodes: [
    { id: 'trigger', type: 'trigger', name: 'Start Sprint' },
    { id: 'requirements', type: 'agent', name: 'Requirements Gathering', agentRole: 'pm',
      artifacts: { consumes: [], produces: [{ id: 'requirements-doc', path: 'docs/requirements.md' }] },
      retry: { maxAttempts: 3, notifyAttempt: 2, retryIntervalMs: 30_000 },
    },
    { id: 'prd', type: 'agent', name: 'PRD Writing', agentRole: 'pm',
      artifacts: { consumes: [{ id: 'requirements-doc' }], produces: [{ id: 'prd-doc', path: 'docs/prd.md' }] },
      retry: { maxAttempts: 3, notifyAttempt: 2, retryIntervalMs: 30_000 },
    },
    { id: 'design', type: 'agent', name: 'Technical Design', agentRole: 'arch',
      artifacts: { consumes: [{ id: 'prd-doc' }], produces: [{ id: 'design-doc', path: 'docs/design.md' }] },
      retry: { maxAttempts: 3, notifyAttempt: 2, retryIntervalMs: 30_000 },
    },
    { id: 'sprint-plan', type: 'agent', name: 'Sprint Planning', agentRole: 'pm',
      artifacts: { consumes: [{ id: 'design-doc' }], produces: [{ id: 'sprint-plan-doc', path: 'docs/sprint-plan.md' }] },
    },
    { id: 'fork', type: 'parallel_fork', name: 'Start Parallel Dev' },
    // 3 static coder slots (unused slots skipped via condition)
    { id: 'check-coder-1', type: 'condition', name: 'Has Task 1?' },
    { id: 'coding-1', type: 'agent', name: 'Coder 1', agentRole: 'coder',
      artifacts: { consumes: [{ id: 'sprint-plan-doc' }], produces: [{ id: 'code-1', path: 'src/feature-1/' }] },
      retry: { maxAttempts: 5, notifyAttempt: 3, retryIntervalMs: 60_000 },
    },
    { id: 'check-coder-2', type: 'condition', name: 'Has Task 2?' },
    { id: 'coding-2', type: 'agent', name: 'Coder 2', agentRole: 'coder',
      artifacts: { consumes: [{ id: 'sprint-plan-doc' }], produces: [{ id: 'code-2', path: 'src/feature-2/' }] },
      retry: { maxAttempts: 5, notifyAttempt: 3, retryIntervalMs: 60_000 },
    },
    { id: 'check-coder-3', type: 'condition', name: 'Has Task 3?' },
    { id: 'coding-3', type: 'agent', name: 'Coder 3', agentRole: 'coder',
      artifacts: { consumes: [{ id: 'sprint-plan-doc' }], produces: [{ id: 'code-3', path: 'src/feature-3/' }] },
      retry: { maxAttempts: 5, notifyAttempt: 3, retryIntervalMs: 60_000 },
    },
    { id: 'join', type: 'join', name: 'Await All Dev' },
    { id: 'qa', type: 'agent', name: 'QA Testing', agentRole: 'qa',
      artifacts: { consumes: [{ id: 'code-1' }, { id: 'code-2' }, { id: 'code-3' }], produces: [{ id: 'qa-report', path: 'docs/qa-report.md' }] },
    },
    { id: 'qa-decision', type: 'condition', name: 'QA Passed?' },
    { id: 'bug-fix', type: 'agent', name: 'Bug Fix', agentRole: 'coder',
      artifacts: { consumes: [{ id: 'qa-report' }], produces: [{ id: 'bug-fix-code', path: 'src/fixes/' }] },
    },
    { id: 'delivery', type: 'human_approval', name: 'Sprint Delivery',
      humanApproval: {
        message: 'Sprint complete. Review and approve for delivery.',
        timeoutMs: 86_400_000,
        onTimeout: 'auto_approve',
        allowedActions: ['approve', 'reject'],
        onReject: 'bug-fix',
      },
    },
  ],
  edges: [
    { from: 'trigger', to: 'requirements' },
    { from: 'requirements', to: 'prd' },
    { from: 'prd', to: 'design' },
    { from: 'design', to: 'sprint-plan' },
    { from: 'sprint-plan', to: 'fork' },
    { from: 'fork', to: 'check-coder-1' },
    { from: 'fork', to: 'check-coder-2' },
    { from: 'fork', to: 'check-coder-3' },
    { from: 'check-coder-1', to: 'coding-1', condition: 'context.coderTasks[0]' },
    { from: 'check-coder-1', to: 'join', condition: '!context.coderTasks[0]' },
    { from: 'check-coder-2', to: 'coding-2', condition: 'context.coderTasks[1]' },
    { from: 'check-coder-2', to: 'join', condition: '!context.coderTasks[1]' },
    { from: 'check-coder-3', to: 'coding-3', condition: 'context.coderTasks[2]' },
    { from: 'check-coder-3', to: 'join', condition: '!context.coderTasks[2]' },
    { from: 'coding-1', to: 'join' },
    { from: 'coding-2', to: 'join' },
    { from: 'coding-3', to: 'join' },
    { from: 'join', to: 'qa' },
    { from: 'qa', to: 'qa-decision' },
    { from: 'qa-decision', to: 'delivery', condition: 'passed' },
    { from: 'qa-decision', to: 'bug-fix', condition: 'failed' },
    { from: 'bug-fix', to: 'qa' },
    { from: 'delivery', to: 'bug-fix', condition: 'rejected' },
  ],
  config: {
    maxParallelNodes: 3,
    defaultTimeoutMs: 1_800_000,
    timers: { workflowPollMs: 30_000, heartbeatMs: 15_000 },
  },
});
